<?php
// CHANGE TO PREPARED STATEMENTS

// make a mysql connection
//$mysqli = new mysqli("mysql.dur.ac.uk", "cwwp64", "H3ather!", "Pcwwp64_Voice");
$mysqli = new mysqli("127.0.0.1", "root", "", "Voice");
if ($mysqli->connect_errno)
{
	die("Failed to connect to MySQL: " . $mysqli->connect_error);
}

$sections = array();

// list the sections
if ($result = $mysqli->query("SELECT * FROM `Section`"))
{
	print('<div id="sections">'."\n");
	while ($row = $result->fetch_assoc())
	{
		printf('<div class="section">');
		printQuestions($mysqli, $row['sectionID']);
		printChoices($mysqli, $row['sectionID']);
		print('</div>'."\n");
	}
	$result->free();
	print('</div>'."\n");
}	
$mysqli->close();

function printQuestions($mysqli, $sectionID)
{
	if ($result = $mysqli->query("SELECT * FROM `Question` WHERE `sectionID`=$sectionID ORDER BY `number`"))
	{
		print('<questions>'."\n");
		while ($row = $result->fetch_assoc())
		{
			printf('<question id="%d" number="%d" description="%s" type="%s"/>'."\n", $row['questionID'], $row['number'], $row['description'], $row['type']);
		}
		$result->free();
		print('</questions>'."\n");
	}	
}

function printChoices($mysqli, $sectionID)
{
	if ($result = $mysqli->query("SELECT * FROM `Choice` WHERE `sectionID`=$sectionID ORDER BY `value`"))
	{
		print('<choices>'."\n");
		while ($row = $result->fetch_assoc())
		{
			printf('<choice id="%d" text="%s" value="%s"/>'."\n", $row['choiceID'], $row['text'], $row['value']);
		}
		$result->free();
		print('</choices>'."\n");
	}	
}
?>